---
# See https://github.com/jvautier/project-cli
fullname: jvautier/vagrant-plugin-boxes
description: Vagrant plugin to handle boxes with yaml [wip]
tags:
  - vagrant
  - vagrant-plugin
  - yaml
github:
  has_issues: true
  has_projects: false
  has_wiki: false
